---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[curl]
      - recipe[scpr-transcoder::default]
    attributes:
      consul:
        service_mode: bootstrap